language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="4d0827bc-4a62-4e82-9f24-e780088f1923"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: alex-sandler@mail.ru
    recipients:
      - rail.shamsemukhametov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
